# Site settings
title: Pass By Value
email: trent.mcclenahan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Passionate about the web and establishing high performing software delivery teams
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tgmcclen
github_username:  tgmcclen

# Build settings
markdown: kramdown
